<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="rajatvera01" ignored="0" name="CustomListener_reRunFailedtest Test" tests="6" failures="2" timestamp="2021-09-11T01:04:18 IST" time="0.045" errors="0">
  <testcase name="TC_01" time="0.006" classname="_41_3_TestNG_Listeners.IRetryAnalyzer_Re_RunFailed_Tests.TestCases"/>
  <testcase name="TC_02" time="0.001" classname="_41_3_TestNG_Listeners.IRetryAnalyzer_Re_RunFailed_Tests.TestCases"/>
  <testcase name="TC_03" time="0.002" classname="_41_3_TestNG_Listeners.IRetryAnalyzer_Re_RunFailed_Tests.TestCases">
    <skipped/>
  </testcase> <!-- TC_03 -->
  <testcase name="TC_03" time="0.001" classname="_41_3_TestNG_Listeners.IRetryAnalyzer_Re_RunFailed_Tests.TestCases">
    <failure type="java.lang.AssertionError" message="Failing TC_03">
      <![CDATA[java.lang.AssertionError: Failing TC_03
at _41_3_TestNG_Listeners.IRetryAnalyzer_Re_RunFailed_Tests.TestCases.TC_03(TestCases.java:19)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- TC_03 -->
  <testcase name="TC_04" time="0.001" classname="_41_3_TestNG_Listeners.IRetryAnalyzer_Re_RunFailed_Tests.TestCases">
    <skipped/>
  </testcase> <!-- TC_04 -->
  <testcase name="TC_04" time="0.001" classname="_41_3_TestNG_Listeners.IRetryAnalyzer_Re_RunFailed_Tests.TestCases">
    <failure type="java.lang.AssertionError" message="Failing TC_04">
      <![CDATA[java.lang.AssertionError: Failing TC_04
at _41_3_TestNG_Listeners.IRetryAnalyzer_Re_RunFailed_Tests.TestCases.TC_04(TestCases.java:25)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- TC_04 -->
</testsuite> <!-- CustomListener_reRunFailedtest Test -->
